### ISSUE TITLE
Expect null arguments to OSGi reference listeners unbind methods

### ISSUE THREAD

**Issue by olaf-otto** [unic/neba#102]
During deployments, NEBA sometimes receives an unexpected null argument to OSGi service listener unbind methods, like so:
````
19.01.2016 08:52:47.880 *WARN* [FelixStartLevel] org.eclipse.gemini.blueprint.config.internal.adapter.CustomListenerAdapterUtils Custom method [public synchronized void io.neba.core.resourcemodels.mapping.AnnotatedFieldMappers.remove(io.neba.api.resourcemodels.AnnotatedFieldMapper)] threw exception when passing service [] java.lang.IllegalArgumentException: Method argument mapper must not be null.
        at io.neba.core.resourcemodels.mapping.AnnotatedFieldMappers.remove(AnnotatedFieldMappers.java:87)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.gemini.blueprint.util.internal.ReflectionUtils.invokeMethod(ReflectionUtils.java:106)
        at org.eclipse.gemini.blueprint.config.internal.adapter.CustomListenerAdapterUtils.invokeCustomMethods(CustomListenerAdapterUtils.java:216)
        at org.eclipse.gemini.blueprint.config.internal.adapter.OsgiServiceLifecycleListenerAdapter.unbind(OsgiServiceLifecycleListenerAdapter.java:320)
        at org.eclipse.gemini.blueprint.service.importer.support.internal.util.OsgiServiceBindingUtils.callListenersUnbind(OsgiServiceBindingUtils.java:67)
        at org.eclipse.gemini.blueprint.service.importer.support.internal.collection.OsgiServiceCollection.afterPropertiesSet(OsgiServiceCollection.java:328)
        at org.eclipse.gemini.blueprint.service.importer.support.OsgiServiceCollectionProxyFactoryBean$1.run(OsgiServiceCollectionProxyFactoryBean.java:211)
        at org.eclipse.gemini.blueprint.service.importer.support.AbstractServiceImporterProxyFactoryBean.getObject(AbstractServiceImporterProxyFactoryBean.java:103)
        at org.eclipse.gemini.blueprint.service.importer.support.OsgiServiceCollectionProxyFactoryBean.getObject(OsgiServiceCollectionProxyFactoryBean.java:80)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:166)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:102)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1467)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:246)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:632)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:934)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$301(AbstractDelegatedExecutionApplicationContext.java:60)
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$1.run(AbstractDelegatedExecutionApplicationContext.java:168)
        at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.normalRefresh(AbstractDelegatedExecutionApplicationContext.java:164)
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$NoDependenciesWaitRefreshExecutor.refresh(AbstractDelegatedExecutionApplicationContext.java:78)
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.refresh(AbstractDelegatedExecutionApplicationContext.java:157)
        at org.eclipse.gemini.blueprint.extender.internal.support.ExtenderConfiguration.start(ExtenderConfiguration.java:170)
        at org.eclipse.gemini.blueprint.extender.internal.boot.ChainActivator.start(ChainActivator.java:93)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2134)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2052)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1279)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Thread.java:745)
````

Analysis shows that this does not yield an inconsistency, i.e. there is nothing that should have been unbound. Apparently, this is to be expected and should not result in an error message.

**Comment by olaf-otto** [comment]
Implemented - done!
