### ISSUE TITLE
System console plugin model registry fails in AEM 6.3

### ISSUE THREAD

**Issue by olaf-otto** [unic/neba#183]
The model registry fails on AEM 6.3. It is the last piece of code to use an administrative resource resolver for historical reasons: Older AEM versions had separate authentication mechanism for the system console, more recent ones leverage the same authentication mechanism for both the JCR and the system console. It should thus be feasible to obtain a resolver with user privileges instead of the administrative resource resolver, or transition to a suitable service user.

```
09.05.2017 21:35:31.976 *ERROR* [qtp212595862-3847] org.apache.felix.http.jetty Exception while processing request to /system/console/modelregistry (java.lang.IllegalStateException: org.apache.sling.api.resource.LoginException: Bundle org.eclipse.gemini.blueprint.extender is NOT whitelisted)
java.lang.IllegalStateException: org.apache.sling.api.resource.LoginException: Bundle org.eclipse.gemini.blueprint.extender is NOT whitelisted
        at io.neba.core.resourcemodels.registration.ModelRegistryConsolePlugin.getResourceResolver(ModelRegistryConsolePlugin.java:237)
        at io.neba.core.resourcemodels.registration.ModelRegistryConsolePlugin.buildCrxDeLinkToResourceType(ModelRegistryConsolePlugin.java:155)
        at io.neba.core.resourcemodels.registration.ModelRegistryConsolePlugin.renderContent(ModelRegistryConsolePlugin.java:141)
        at org.apache.felix.webconsole.AbstractWebConsolePlugin.doGet(AbstractWebConsolePlugin.java:194)
        at io.neba.core.resourcemodels.registration.ModelRegistryConsolePlugin.doGet(ModelRegistryConsolePlugin.java:95)
       
--- snipp --

Caused by: org.apache.sling.api.resource.LoginException: Bundle org.eclipse.gemini.blueprint.extender is NOT whitelisted
        at org.apache.sling.jcr.resource.internal.helper.jcr.JcrProviderStateFactory.getLoginException(JcrProviderStateFactory.java:203)
        at org.apache.sling.jcr.resource.internal.helper.jcr.JcrProviderStateFactory.createProviderState(JcrProviderStateFactory.java:136)
        at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.authenticate(JcrResourceProvider.java:284)
        at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.authenticate(JcrResourceProvider.java:75)
        at org.apache.sling.resourceresolver.impl.providers.stateful.ProviderManager.authenticate(ProviderManager.java:161)
        at org.apache.sling.resourceresolver.impl.providers.stateful.ProviderManager.getOrCreateProvider(ProviderManager.java:87)
        at org.apache.sling.resourceresolver.impl.providers.stateful.ProviderManager.authenticateAll(ProviderManager.java:129)
        at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.createControl(ResourceResolverImpl.java:138)
        at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.<init>(ResourceResolverImpl.java:100)
        at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.<init>(ResourceResolverImpl.java:94)

```

**Comment by olaf-otto** [comment]
The issue arises as using `ResourceResolverFactory#getAdministrativeResourceResolver` and `SlingRepository#loginAdministrative` are only available to explicitly white listed bundles as per AEM 6.3.

The solution options are:

1. Create a system user (rep:SystemUser), authorize it and configure and use a user mapping to obtain a ResourceResolver or Session with the respective privileges (https://sling.apache.org/documentation/the-sling-engine/service-authentication.html).
2. Use an existing system user, e.g. `sling-scripting`
2. Try using the credentials of the user logged into the web console
3. White list the bundle using the administrative resource resolver

For solution 1, a service user could be created programatically ([using sling content loading](https://sling.apache.org/documentation/bundles/content-loading-jcr-contentloader.html) does not work, as creating a rep:SystemUser means setting protected properties such as rep:principalName, which is not possible via content loading). However, this requires administrative privileges, resulting in a chicken-and-egg problem. A system user can also be created using the Sling provisioning model (http://sling.apache.org/documentation/bundles/repository-initialization.html). However, this is not an option for existing / AEM installations and could not be shipped inside a delivery package / bundle.
  
Solution 2. Would mean piggybacking on a service user designed for a different purpose, which would be a bad idea.

Thus, solution 3 is the only remaining option.  Resulting, NEBA core will ship a config white listing the bundle to explicitly allow usage of an administrative resource resolver (https://sling.apache.org/documentation/the-sling-engine/service-authentication.html#whitelisting-bundles-for-administrative-login). Since the resolver is exclusively used for read-only access in a web console plugin, the usage is safe.

**Comment by olaf-otto** [comment]
Fixed - done!
