### ISSUE TITLE
Handling of context failed events is synchronous, but should be asynchronous

### ISSUE THREAD

**Issue by olaf-otto** [unic/neba#199]
To handle locking issues in Apache Felix in conjunction with asynchronous context creation and destruction, NEBA ships with a custom task executor (the Felix task executor, see https://www.eclipse.org/gemini/blueprint/documentation/reference/2.1.0.RELEASE/html/app-deploy.html#app-deploy:extender-configuration).

This executor is expected to be used exclusively for context creation / shutdown by gemini blueprint. However, it is alsoused for the execution of other tasks that should be asynchronous, e.g. invocations of methods annotated with @Asnychronous as, contrary to the documentation of task:annotation-driven, [org.springframework.aop.interceptor.AsyncExecutionAspectSupport](http://docs.spring.io/spring/docs/4.3.x/javadoc-api/org/springframework/aop/interceptor/AsyncExecutionAspectSupport.html) obtains either the only taskExecutor present in the application context or, if more than one are available, the task executor named "taskExecutor".

This can, in case a bundle runs into a timeout due to missing service dependencies and SCR shutdowns also acquire certain locks, result in a temporary deadlock that slows down bundle shutdown, such that it may take minutes. 

Here, NEBA core needs to make sure that it's internal asynchronous tasks do not use the Felix Task Executor, but are actually asynchronous.

Here is a related stack trace capturing such a situation:

```
"qtp115733586-207" #207 prio=5 os_prio=0 tid=0x0000000069db5800 nid=0x1f10 waiting on condition [0x0000000000207000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000009f872e18> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
        at org.apache.felix.scr.impl.Activator$ScrExtension.destroy(Activator.java:268)
        at org.apache.felix.utils.extender.AbstractExtender$2.run(AbstractExtender.java:290)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at org.apache.felix.utils.extender.AbstractExtender$2.run(AbstractExtender.java:290)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.felix.utils.extender.AbstractExtender.destroyExtension(AbstractExtender.java:312)
        at org.apache.felix.utils.extender.AbstractExtender.bundleChanged(AbstractExtender.java:186)
        at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:913)
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
        at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4531)
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2597)
        at org.apache.felix.framework.BundleImpl.stop(BundleImpl.java:1013)
        at org.apache.felix.framework.BundleImpl.stop(BundleImpl.java:1000)
        at io.neba.core.blueprint.ContextFailedHandler.stop(ContextFailedHandler.java:66)
        at io.neba.core.blueprint.ContextFailedHandler.onOsgiApplicationEvent(ContextFailedHandler.java:59)
        at io.neba.core.blueprint.ContextFailedHandler$$FastClassBySpringCGLIB$$49f919b8.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at io.neba.core.blueprint.FelixTaskExecutor.execute(FelixTaskExecutor.java:37)
        at org.springframework.core.task.support.TaskExecutorAdapter.doExecute(TaskExecutorAdapter.java:173)
        at org.springframework.core.task.support.TaskExecutorAdapter.submit(TaskExecutorAdapter.java:124)
        at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.doSubmit(AsyncExecutionAspectSupport.java:273)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.invoke(AsyncExecutionInterceptor.java:130)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at io.neba.core.blueprint.ContextFailedHandler$$EnhancerBySpringCGLIB$$c12a014b.onOsgiApplicationEvent(<generated>)
        at org.eclipse.gemini.blueprint.context.event.ApplicationListenerAdapter.onApplicationEvent(ApplicationListenerAdapter.java:53)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
        at org.eclipse.gemini.blueprint.context.event.OsgiBundleApplicationContextEventMulticasterAdapter.multicastEvent(OsgiBundleApplicationContextEventMulticasterAdapter.java:55)
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.sendFailedEvent(AbstractDelegatedExecutionApplicationContext.java:654)
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.completeRefresh(AbstractDelegatedExecutionApplicationContext.java:347)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$CompleteRefreshTask.run(DependencyWaiterApplicationContextExecutor.java:137)
        at io.neba.core.blueprint.FelixTaskExecutor.execute(FelixTaskExecutor.java:37)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.stageTwo(DependencyWaiterApplicationContextExecutor.java:311)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$2.run(DependencyWaiterApplicationContextExecutor.java:244)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyServiceManager$DependencyServiceListener.serviceChanged(DependencyServiceManager.java:153)
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:987)
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
        at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4547)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3521)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:869)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:857)
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:915)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:715)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:950)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:911)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1215)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1136)
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:945)
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:881)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1167)
        at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:120)
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:987)
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
        at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4547)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3521)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
...skipping...
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.felix.utils.extender.AbstractExtender.destroyExtension(AbstractExtender.java:312)
        at org.apache.felix.utils.extender.AbstractExtender.bundleChanged(AbstractExtender.java:186)
        at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:913)
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
        at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4531)
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2597)
        at org.apache.felix.framework.BundleImpl.stop(BundleImpl.java:1013)
        at org.apache.felix.framework.BundleImpl.stop(BundleImpl.java:1000)
        at io.neba.core.blueprint.ContextFailedHandler.stop(ContextFailedHandler.java:66)
        at io.neba.core.blueprint.ContextFailedHandler.onOsgiApplicationEvent(ContextFailedHandler.java:59)
        at io.neba.core.blueprint.ContextFailedHandler$$FastClassBySpringCGLIB$$49f919b8.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at io.neba.core.blueprint.FelixTaskExecutor.execute(FelixTaskExecutor.java:37)
        at org.springframework.core.task.support.TaskExecutorAdapter.doExecute(TaskExecutorAdapter.java:173)
        at org.springframework.core.task.support.TaskExecutorAdapter.submit(TaskExecutorAdapter.java:124)
        at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.doSubmit(AsyncExecutionAspectSupport.java:273)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.invoke(AsyncExecutionInterceptor.java:130)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at io.neba.core.blueprint.ContextFailedHandler$$EnhancerBySpringCGLIB$$c12a014b.onOsgiApplicationEvent(<generated>)
        at org.eclipse.gemini.blueprint.context.event.ApplicationListenerAdapter.onApplicationEvent(ApplicationListenerAdapter.java:53)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
        at org.eclipse.gemini.blueprint.context.event.OsgiBundleApplicationContextEventMulticasterAdapter.multicastEvent(OsgiBundleApplicationContextEventMulticasterAdapter.java:55)
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.sendFailedEvent(AbstractDelegatedExecutionApplicationContext.java:654)
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.completeRefresh(AbstractDelegatedExecutionApplicationContext.java:347)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$CompleteRefreshTask.run(DependencyWaiterApplicationContextExecutor.java:137)
        at io.neba.core.blueprint.FelixTaskExecutor.execute(FelixTaskExecutor.java:37)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.stageTwo(DependencyWaiterApplicationContextExecutor.java:311)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$2.run(DependencyWaiterApplicationContextExecutor.java:244)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyServiceManager$DependencyServiceListener.serviceChanged(DependencyServiceManager.java:153)
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:987)
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
        at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4547)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3521)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:869)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:857)
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:915)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:715)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:950)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:911)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1215)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1136)
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:945)
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:881)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1167)
        at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:120)
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:987)
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
        at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4547)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3521)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
```

**Comment by olaf-otto** [comment]
Fixed, done!
