### ISSUE TITLE
Log viewer: Sling 9 is missing org.eclipse.jetty.util.DecoratedObjectFactory in ServletContext

### ISSUE THREAD

**Issue by olaf-otto** [unic/neba#209]
With Sling 9, the presence of  a org.eclipse.jetty.util.DecoratedObjectFactory is required in the ServletContext. Thus, such an instance must be provided  by the log viewer.
```
...
Caused by: java.lang.IllegalStateException: Unable to find required ServletContext attribute: org.eclipse.jetty.util.DecoratedObjectFactory
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.doStart(WebSocketServerFactory.java:313)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.websocket.servlet.WebSocketServlet.init(WebSocketServlet.java:142)
        ... 45 common frames omitted
```

**Comment by olaf-otto** [comment]
Fixed, done!

**Comment by olaf-otto** [comment]
Re-opening: It appears accessing the ServletContext service may result in an implicit deadlock, depending on the order of service startup:

```
"FelixStartLevel" #19 daemon prio=5 os_prio=0 tid=0x000000001c7f0000 nid=0x3110 in Object.wait() [0x000000001e7ad000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at org.eclipse.gemini.blueprint.service.importer.support.internal.support.RetryTemplate.execute(RetryTemplate.java:104)
        - locked <0x00000000f4032f18> (a java.lang.Object)
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceDynamicInterceptor.lookupService(ServiceDynamicInterceptor.java:427)
        - locked <0x00000000f4032f18> (a java.lang.Object)
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceDynamicInterceptor.getTarget(ServiceDynamicInterceptor.java:400)
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70)
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy27.getAttribute(Unknown Source)
        at io.neba.core.logviewer.LogfileViewerConsolePlugin.injectDecoratorObjectFactoryIntoServletContext(LogfileViewerConsolePlugin.java:76)
```

**Comment by olaf-otto** [comment]
Fixed - done!
