### ISSUE TITLE
Harden ReferenceConsistencyChecker against invalid bundle contexts

### ISSUE THREAD

**Issue by SebastianLisken** [unic/neba#37]
There's an error that currently crops up every 30s in a live CQ instance, caused by a scheduled background task. As requested by Olaf, here is the stack trace.

    18.02.2015 20:04:55.215 *ERROR* [pool-4-thread-1] org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler Unexpected error occurred in scheduled task. java.lang.IllegalStateException: Invalid BundleContext.
            at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:365)
            at org.apache.felix.framework.BundleContextImpl.getBundle(BundleContextImpl.java:137)
            at io.neba.core.blueprint.ReferenceConsistencyChecker.getBundle(ReferenceConsistencyChecker.java:52)
            at io.neba.core.blueprint.ReferenceConsistencyChecker.isValid(ReferenceConsistencyChecker.java:41)
            at io.neba.core.resourcemodels.registration.ModelRegistry.removeInvalidReferences(ModelRegistry.java:383)
            at sun.reflect.GeneratedMethodAccessor287.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
            at java.lang.reflect.Method.invoke(Method.java:597)
            at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
            at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
            at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
            at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:181)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:205)
            at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
            at java.lang.Thread.run(Thread.java:619)

**Comment by olaf-otto** [comment]
IT would be interesting to know how the bundle context became invalid in the first place... However, the  consistency checker must be hardened regardless.

**Comment by olaf-otto** [comment]
I've taken a look at the felix bundle context implementation to better understand how this happens. First of, this only happens on _very_ old version of Felix (e.g. those shipped with CQ 5.3). It seems to me that this is a felix-internal issue, perhaps because the NEBA bundle is a fragment. Here is the code excerpt from [1]:

```    
353    private void More ...checkValidity()
354    {
355        if (m_valid)
356        {
357            switch (m_bundle.getState())
358            {
359                case Bundle.ACTIVE:
360                case Bundle.STARTING:
361                case Bundle.STOPPING:
362                    return;
363            }
364        }
365
366        throw new IllegalStateException("Invalid BundleContext.");
367    }
```

Unfortunately, the exception does not tell what the unexpected state is.


[1] http://grepcode.com/file/repo1.maven.org/maven2/org.apache.felix/org.apache.felix.framework/2.0.5/org/apache/felix/framework/BundleContextImpl.java#BundleContextImpl.checkValidity%28%29

**Comment by olaf-otto** [comment]
After some analysis, I have come to the conclusion that the reference checker itself may be discarded due to an earlier architecture change.

When a bundle is stopped or fails, the ContextShutdownHandler removes all data related to the bundle from all registries. Consequently, it is safe to store a reference to the source bundle in the OsgiBeanSource. This makes it possible to simply check the validity there - which is also much better from an OO point of view:

Before:

    consistencyChecker.isValid(source)

After:

    source.isValid();

I'll put this on a feature branch.

**Comment by olaf-otto** [comment]
Done - merged pull request.
