### ISSUE TITLE
Log file viewer exhibits NPE in pure Sling if the "Apache Sling Logging Configuration" is not persitent

### ISSUE THREAD

**Issue by olaf-otto** [unic/neba#39]
The log file viewer attempts to determine the configured log file directory using the apache sling logger configuration. However, the configuration is not persistent in pure Sling but falls back to the implementation's default (${sling.home}/logs). This leads to an NPE:

```
org.eclipse.jetty.servlet.ServletHandler /system/console/logviewer
java.lang.NullPointerException: null
        at io.neba.core.logviewer.LogfileViewerConsolePlugin.getConfiguredLogfile(LogfileViewerConsolePlugin.java:337)
        at io.neba.core.logviewer.LogfileViewerConsolePlugin.getLogfileDirectory(LogfileViewerConsolePlugin.java:328)
        at io.neba.core.logviewer.LogfileViewerConsolePlugin.resolveLogFiles(LogfileViewerConsolePlugin.java:286)
```
It must thus be expected that the properties of the configuration is null.

**Comment by olaf-otto** [comment]
Fixed in 3.5.0
